"use client";

import React, { useState, useEffect, useMemo, Suspense } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import { BIBLE_BOOKS, findBook, extractBibleText, searchBibleVerses, type BibleVerse, USE_WEB_BIBLE, getBookName } from "@/lib/bible";
import { useLanguage } from "@/lib/i18n";

const AiDisclaimer = ({ language }: { language: string }) => {
  if (language === "zh") {
    return (
      <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50/50 p-3.5 text-xs text-slate-800 leading-relaxed shadow-sm">
        <div className="flex items-start gap-2.5">
          <span className="text-amber-600 text-base mt-0.5">⚠️</span>
          <div>
            <p className="font-bold text-amber-800 mb-0.5">AI 自动翻译</p>
            <p className="text-slate-600 leading-normal">
              本页面的中文内容是由人工智能 (AI) 自动翻译生成，仅用于帮助读者理解圣经。这<b>不是</b>官方发行的中文圣经译本。
            </p>
          </div>
        </div>
      </div>
    );
  }
  if (language === "en") {
    return (
      <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50/50 p-3.5 text-xs text-slate-800 leading-relaxed shadow-sm">
        <div className="flex items-start gap-2.5">
          <span className="text-amber-600 text-base mt-0.5">⚠️</span>
          <div>
            <p className="font-bold text-amber-800 mb-0.5">AI Automatic Translation</p>
            <p className="text-slate-600 leading-normal">
              The translation on this page is automatically generated by Artificial Intelligence (AI) to assist readers. This is <b>NOT</b> an official Bible translation.
            </p>
          </div>
        </div>
      </div>
    );
  }
  return (
    <div className="mb-4 rounded-xl border border-amber-200 bg-amber-50/50 p-3.5 text-xs text-slate-800 leading-relaxed shadow-sm">
      <div className="flex items-start gap-2.5">
        <span className="text-amber-600 text-base mt-0.5">⚠️</span>
        <div>
          <p className="font-bold text-amber-800 mb-0.5">Terjemahan Otomatis AI</p>
          <p className="text-slate-600 leading-normal">
            Terjemahan Bahasa Indonesia pada halaman ini merupakan hasil terjemahan otomatis menggunakan Artificial Intelligence (AI).
            Terjemahan ini disediakan untuk membantu pembaca memahami isi Alkitab. Terjemahan ini <b>BUKAN</b> merupakan terjemahan resmi dalam Bahasa Indonesia.
          </p>
        </div>
      </div>
    </div>
  );
};

function BibleContent() {
  const { language } = useLanguage();
  const searchParams = useSearchParams();
  const router = useRouter();

  const tLocal = (key: string) => {
    const dict: Record<string, Record<string, string>> = {
      back: { id: "← Kembali ke Alkitab / TMA", en: "← Back to Bible / TMA", zh: "← 返回圣经 / TMA" },
      home: { id: "🏠 Beranda Mini App", en: "🏠 Mini App Home", zh: "🏠 小程序首页" },
      title: { id: "Alkitab Online", en: "Online Bible", zh: "在线圣经" },
      version: { id: "Versi", en: "Version", zh: "版本" },
      searchLabel: { id: "Pencarian Alkitab (Referensi atau Kata Kunci)", en: "Bible Search (Reference or Keyword)", zh: "圣经搜索 (参考或关键词)" },
      searchPlaceholder: { id: "Cari 'Mazmur 23', 'Yoh 3:16-18', atau 'kasih'", en: "Search 'Psalm 23', 'John 3:16', or 'love'", zh: "搜索 '诗篇 23', '约翰福音 3:16', 或 '爱'" },
      searchBtn: { id: "Cari", en: "Search", zh: "搜索" },
      searchHint: { id: "Contoh: ketik \"Matius 5:1-12\" untuk pasal/ayat, atau \"damai\" untuk cari kata kunci.", en: "Example: type \"Matthew 5:1-12\" for chapter/verses, or \"peace\" for keyword search.", zh: "示例：输入 \"马太福音 5:1-12\" 获取章节/经文，或输入 \"和平\" 进行关键词搜索。" },
      loading: { id: "Memuat Alkitab...", en: "Loading Bible...", zh: "正在加载圣经..." },
      init: { id: "Inisialisasi Alkitab...", en: "Initializing Bible...", zh: "正在初始化圣经..." },
      noResults: { id: "Tidak ada ayat yang cocok dengan kata kunci tersebut.", en: "No verses match this keyword.", zh: "没有符合该关键词的经文。" },
      searchError: { id: "Gagal melakukan pencarian kata kunci.", en: "Failed to perform keyword search.", zh: "无法进行关键词搜索。" },
      resultsTitle: { id: "Hasil Pencarian: {count} ayat ditemukan", en: "Search Results: {count} verses found", zh: "搜索结果：找到 {count} 节经文" },
      listen: { id: "Dengarkan", en: "Listen", zh: "听" },
      stop: { id: "Hentikan", en: "Stop", zh: "停止" },
      fontSmaller: { id: "Perkecil teks", en: "Smaller text", zh: "缩小字体" },
      fontLarger: { id: "Perbesar teks", en: "Larger text", zh: "放大字体" },
      voiceSearchHint: { id: "Cari menggunakan suara (Voice to Text)", en: "Voice search (Voice to Text)", zh: "语音搜索 (语音转文字)" },
      unrecognizedBook: { id: "Suara terdeteksi: \"{text}\". Kitab tidak dikenali.", en: "Voice detected: \"{text}\". Book not recognized.", zh: "检测到语音：\"{text}\"。未识别的书卷。" },
      supportedLanguageMsg: { id: "Browser Anda tidak mendukung perekaman suara (Speech Recognition).", en: "Your browser does not support Speech Recognition.", zh: "您的浏览器不支持语音识别。" }
    };
    return dict[key]?.[language] || dict[key]?.id || key;
  };

  // Search input state
  const [searchQuery, setSearchQuery] = useState("");
  const [isListening, setIsListening] = useState(false);

  const startVoiceSearch = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert(tLocal("supportedLanguageMsg"));
      return;
    }
    const recognition = new SpeechRecognition();
    recognition.lang = language === "zh" ? "zh-CN" : language === "en" ? "en-US" : "id-ID";
    recognition.interimResults = false;
    recognition.maxAlternatives = 1;

    recognition.onstart = () => {
      setIsListening(true);
    };

    recognition.onresult = async (event: any) => {
      let text = event.results[0][0].transcript.trim();
      if (!text) return;

      text = text.toLowerCase()
        .replace(/\bpasal\b/g, "")
        .replace(/\bayat\b/g, ":")
        .replace(/\bsampai\b/g, "-")
        .replace(/\bhingga\b/g, "-")
        .replace(/\bsatu\b/g, "1")
        .replace(/\bdua\b/g, "2")
        .replace(/\btiga\b/g, "3")
        .replace(/\bempat\b/g, "4")
        .replace(/\blima\b/g, "5")
        .replace(/\benam\b/g, "6")
        .replace(/\btujuh\b/g, "7")
        .replace(/\bdelapan\b/g, "8")
        .replace(/\bsembilan\b/g, "9")
        .replace(/\bsepuluh\b/g, "10");

      let detectedBook = "";
      let foundIndex = -1;

      const normalizedText = text.toLowerCase();
      for (const b of BIBLE_BOOKS) {
        const bookLower = b.name.toLowerCase();
        if (normalizedText.includes(bookLower)) {
          detectedBook = b.name;
          foundIndex = normalizedText.indexOf(bookLower);
          break;
        }
      }

      if (detectedBook) {
        const afterBook = text.substring(foundIndex + detectedBook.length).trim();
        const numRegex = /^(\d+)(?:\s*[:\s]\s*(\d+)(?:\s*-\s*(\d+))?)/;
        const match = afterBook.match(numRegex);
        
        let parsedChapter = "1";
        let parsedVerse = "";
        
        if (match) {
          parsedChapter = match[1];
          if (match[2]) {
            parsedVerse = match[2];
            if (match[3]) {
              parsedVerse += `-${match[3]}`;
            }
          }
        }
        
        const finalQuery = `${detectedBook} ${parsedChapter}${parsedVerse ? `:${parsedVerse}` : ""}`;
        setSearchQuery(finalQuery);
        await loadChapterData(detectedBook, parsedChapter, parsedVerse);
      } else {
        setSearchQuery(event.results[0][0].transcript);
      }
    };

    recognition.onerror = (event: any) => {
      console.error("Speech recognition error:", event.error);
    };

    recognition.onend = () => {
      setIsListening(false);
    };

    recognition.start();
  };

  const [statusMessage, setStatusMessage] = useState("");
  const [loading, setLoading] = useState(false);

  // Loaded chapter details
  const [loadedChapter, setLoadedChapter] = useState<any>(null);
  const [highlightedVerses, setHighlightedVerses] = useState<number[]>([]);
  const [keywordResults, setKeywordResults] = useState<BibleVerse[]>([]);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [fontSize, setFontSize] = useState(16);

  // TTS — Dengarkan Alkitab (Text-to-Speech)
  const [isSpeaking, setIsSpeaking] = useState(false);

  const normalizeTtsText = (text: string) =>
    text
      // Perbaiki ejaan umum agar TTS melafalkan dengan bunyi 'a' (Alah) bukan 'o' (Alloh)
      .replace(/ALLAH/g, "ALAH")
      .replace(/Allah/g, "Alah")
      .replace(/allah/g, "alah")
      .replace(/ALLOH/g, "ALAH")
      .replace(/Alloh/g, "Alah")
      .replace(/alloh/g, "alah")
      .replace(/—/g, ", ").replace(/–/g, ", ")
      .replace(/\.\.\./g, ". ").replace(/[""]/g, "").replace(/\*/g, "");

  const speakChapter = () => {
    if (typeof window === "undefined" || !window.speechSynthesis) {
      alert("Browser Anda tidak mendukung Text-to-Speech.");
      return;
    }
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }
    if (!loadedChapter) return;

    const verses = (loadedChapter.chapter?.content || [])
      .filter((item: any) => item.type === "verse")
      .map((item: any) => `${tLocal("listen")} ${item.number}. ${extractBibleText(item.content)}`)
      .join(" ");
    const label = `${getBookName(loadedChapter.book?.name || "", language)} ${loadedChapter.chapter?.number || ""}`;
    const fullText = normalizeTtsText(`${label}. ${verses}`);

    const utter = new SpeechSynthesisUtterance(fullText);
    utter.lang = language === "zh" ? "zh-CN" : language === "en" ? "en-US" : "id-ID";
    utter.rate = 0.85;
    utter.pitch = 1.0;
    const voices = window.speechSynthesis.getVoices();
    const voiceLang = language === "zh" ? "zh" : language === "en" ? "en" : "id";
    const targetVoice = voices.find(v => v.lang.startsWith(voiceLang) || v.lang.startsWith("ms"));
    if (targetVoice) utter.voice = targetVoice;

    utter.onstart = () => setIsSpeaking(true);
    utter.onend = () => setIsSpeaking(false);
    utter.onerror = () => setIsSpeaking(false);
    window.speechSynthesis.speak(utter);
  };

  // Helper to parse verse range e.g. "1-2" or "3"
  const parseVerseNumbers = (verseStr: string): number[] => {
    if (!verseStr || !verseStr.trim()) return [];
    const nums: number[] = [];
    const parts = verseStr.trim().split(/[\s,-]+/);
    if (parts.length === 1) {
      const single = parseInt(parts[0], 10);
      if (!isNaN(single)) nums.push(single);
    } else if (parts.length >= 2) {
      const start = parseInt(parts[0], 10);
      const end = parseInt(parts[1], 10);
      if (!isNaN(start) && !isNaN(end)) {
        for (let i = Math.min(start, end); i <= Math.max(start, end); i++) {
          nums.push(i);
        }
      }
    }
    return nums;
  };

  // Main loader for a specific book and chapter
  const loadChapterData = async (bookName: string, chapterNum: string, highlightVerseStr: string = "") => {
    setLoading(true);
    setErrorMessage(null);
    setLoadedChapter(null);
    setKeywordResults([]);

    const book = findBook(bookName);
    if (!book) {
      setErrorMessage(tLocal("noResults"));
      setLoading(false);
      return;
    }

    const bookId = book.id;
    const chap = parseInt(chapterNum, 10) || 1;
    const highlights = parseVerseNumbers(highlightVerseStr);
    setHighlightedVerses(highlights);

    const transId = language === "zh"
      ? "zh_web"
      : language === "en"
      ? (USE_WEB_BIBLE ? "web" : "BSB")
      : (USE_WEB_BIBLE ? "ind_web" : "ind_ayt");

    // 1. Try local fetch
    try {
      const res = await fetch(`/bible/${transId}/${bookId}/${chap}.json`);
      if (res.ok) {
        const data = await res.json();
        if (data && data.chapter) {
          setLoadedChapter(data);
          setLoading(false);
          // Scroll to highlighted verse after render
          if (highlights.length > 0) {
            setTimeout(() => {
              const el = document.getElementById(`v-${highlights[0]}`);
              if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
            }, 300);
          }
          return;
        }
      }
    } catch (err) {
      console.warn("Local fetch failed, trying R2...", err);
    }

    // 2. Try R2 backup proxy
    try {
      const res = await fetch(`/api/backup?file=bible/${transId}/${bookId}/${chap}.json`);
      if (res.ok) {
        const data = await res.json();
        if (data && data.chapter) {
          setLoadedChapter(data);
          setLoading(false);
          if (highlights.length > 0) {
            setTimeout(() => {
              const el = document.getElementById(`v-${highlights[0]}`);
              if (el) el.scrollIntoView({ behavior: "smooth", block: "center" });
            }, 300);
          }
          return;
        }
      }
    } catch (err) {
      console.error("R2 fetch failed:", err);
    }

    setErrorMessage(tLocal("searchError"));
    setLoading(false);
  };

  // Regex to detect verse format like "Yohanes 3:16", "Matius 1:2-4"
  const parsedBibleRef = useMemo(() => {
    if (!searchQuery.trim()) return null;
    const clean = searchQuery.trim();
    const regex = /^((?:\d\s*)?[a-zA-Z\u00C0-\u024F\u4e00-\u9fa5]+(?:\s+[a-zA-Z\u00C0-\u024F\u4e00-\u9fa5]+)*)\s+(\d+)[:\s]+(\d+)(?:-(\d+))?$/i;
    const match = clean.match(regex);
    if (match) {
      return {
        book: match[1].trim(),
        chapter: parseInt(match[2]),
        verseStart: parseInt(match[3]),
        verseEnd: match[4] ? parseInt(match[4]) : undefined,
        rawString: clean
      };
    }
    // Also support book + chapter format like "Yohanes 3"
    const regexChapOnly = /^((?:\d\s*)?[a-zA-Z\u00C0-\u024F\u4e00-\u9fa5]+(?:\s+[a-zA-Z\u00C0-\u024F\u4e00-\u9fa5]+)*)\s+(\d+)$/i;
    const matchChap = clean.match(regexChapOnly);
    if (matchChap) {
      return {
        book: matchChap[1].trim(),
        chapter: parseInt(matchChap[2]),
        verseStart: 1,
        verseEnd: undefined,
        rawString: clean,
        isChapterOnly: true
      };
    }
    return null;
  }, [searchQuery]);

  // Execute search based on input query
  const handleSearchSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    const query = searchQuery.trim();
    if (!query) return;

    const transId = language === "zh"
      ? "zh_web"
      : language === "en"
      ? (USE_WEB_BIBLE ? "web" : "BSB")
      : (USE_WEB_BIBLE ? "ind_web" : "ind_ayt");

    if (parsedBibleRef) {
      const verseRange = parsedBibleRef.isChapterOnly 
        ? "" 
        : parsedBibleRef.verseStart.toString() + (parsedBibleRef.verseEnd ? `-${parsedBibleRef.verseEnd}` : "");
      await loadChapterData(parsedBibleRef.book, parsedBibleRef.chapter.toString(), verseRange);
    } else {
      // Keyword search
      setLoading(true);
      setErrorMessage(null);
      setLoadedChapter(null);
      try {
        const results = await searchBibleVerses(query, transId);
        setKeywordResults(results);
        if (results.length === 0) {
          setErrorMessage(tLocal("noResults"));
        }
      } catch (err) {
        console.error("Search failed:", err);
        setErrorMessage(tLocal("searchError"));
      } finally {
        setLoading(false);
      }
    }
  };

  // Load verse from query params on mount
  useEffect(() => {
    const book = searchParams.get("book");
    const chapter = searchParams.get("chapter");
    const verse = searchParams.get("verse");

    if (book && chapter) {
      const defaultSearch = `${book} ${chapter}${verse ? `:${verse}` : ""}`;
      setSearchQuery(defaultSearch);
      loadChapterData(book, chapter, verse || "");
    } else {
      // Default view
      setSearchQuery(language === "zh" ? "约翰福音 3:16" : language === "en" ? "John 3:16" : "Yohanes 3:16");
      loadChapterData(language === "zh" ? "约翰福音" : language === "en" ? "John" : "Yohanes", "3", "16");
    }
  }, [searchParams, language]);

  return (
    <div className="flex-1 max-w-2xl mx-auto w-full px-5 py-6 flex flex-col min-h-screen">
      {/* Action Buttons (Header Nav) */}
      <div className="flex items-center justify-between border-b border-gray-200 pb-4 mb-6 shrink-0">
        <Link
          href="/telegram-miniapp?menu=alkitab"
          className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gray-100 hover:bg-gray-200 text-sm font-semibold text-gray-800 transition active:scale-95 border border-gray-200"
        >
          {tLocal("back")}
        </Link>
        <Link
          href="/telegram-miniapp"
          className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gray-100 hover:bg-gray-200 text-sm font-semibold text-gray-800 transition active:scale-95 border border-gray-200"
        >
          {tLocal("home")}
        </Link>
      </div>

      {/* Title */}
      <div className="mb-6 text-center">
        <h1 className="text-2xl font-extrabold text-black font-serif">{tLocal("title")}</h1>
        <p className="text-xs text-gray-500 mt-1 uppercase tracking-wider font-semibold">
          {tLocal("version")}: {
            language === "zh"
              ? "和合本 (CUV)"
              : language === "en"
              ? (USE_WEB_BIBLE ? "World English Bible (WEB)" : "Berean Standard Bible (BSB)")
              : (USE_WEB_BIBLE ? "World English Bible Terjemahan AI (WEB-AI)" : "Alkitab Yang Terbuka (AYT)")
          }
        </p>
      </div>

      {/* Bible Search Bar */}
      <form onSubmit={handleSearchSubmit} className="mb-6 bg-gray-50 border border-gray-200 rounded-2xl p-4 shadow-sm shrink-0">
        <label className="block text-xs font-bold text-gray-700 uppercase tracking-wider mb-2">
          {tLocal("searchLabel")}
        </label>
        <div className="flex gap-2">
          <div className="flex-1 relative">
            <input
              type="text"
              className="w-full bg-white border border-gray-300 rounded-xl py-2.5 pl-4 pr-11 text-sm text-black placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-teal-600 focus:border-transparent transition"
              placeholder={tLocal("searchPlaceholder")}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
            <button
              type="button"
              onClick={startVoiceSearch}
              className={`absolute inset-y-0 right-0 pr-3.5 flex items-center transition-all duration-300 hover:scale-110 active:scale-95 ${
                isListening 
                  ? "text-red-500 animate-pulse" 
                  : "text-gray-400 hover:text-teal-650"
              }`}
              title={tLocal("voiceSearchHint")}
            >
              {isListening ? (
                <span className="w-5 h-5 flex items-center justify-center bg-red-500/20 rounded-full text-xs">🔴</span>
              ) : (
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="w-5 h-5">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 18.75a6 6 0 006-6v-1.5m-6 7.5a6 6 0 01-6-6v-1.5m6 7.5v3.75m-3.75 0h7.5M12 15.75a3 3 0 01-3-3V4.5a3 3 0 116 0v8.25a3 3 0 01-3 3z" />
                </svg>
              )}
            </button>
          </div>
          <button
            type="submit"
            className="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2.5 px-5 rounded-xl text-sm transition active:scale-95 shadow-sm"
          >
            {tLocal("searchBtn")}
          </button>
        </div>
        <p className="text-[10px] text-gray-500 mt-2 italic">
          {tLocal("searchHint")}
        </p>
      </form>

      {/* Results / Reader Area */}
      <div className="flex-1 flex flex-col bg-white border border-gray-200 rounded-2xl p-5 shadow-sm min-h-[350px]">
        {USE_WEB_BIBLE && language === "id" && <AiDisclaimer language={language} />}
        {loading && (
          <div className="flex-1 flex flex-col items-center justify-center py-12 text-gray-500 text-sm italic">
            <span className="w-8 h-8 border-4 border-teal-600 border-t-transparent rounded-full animate-spin mb-3"></span>
            <span>{tLocal("loading")}</span>
          </div>
        )}

        {errorMessage && !loading && (
          <div className="flex-1 flex items-center justify-center text-center p-6 bg-red-50 border border-red-100 rounded-xl">
            <p className="text-sm font-semibold text-red-600">{errorMessage}</p>
          </div>
        )}

        {/* Chapter View */}
        {loadedChapter && !loading && (
          <div className="space-y-5">
            <div className="flex items-center justify-between border-b border-gray-200 pb-3">
              <h2 className="text-xl font-bold text-black font-serif">
                {getBookName(loadedChapter.book?.name || "", language)} {loadedChapter.chapter?.number}
              </h2>
              
              <div className="flex items-center gap-2.5">
                {/* Font Size controls */}
                <div className="flex items-center border border-gray-300 rounded-lg overflow-hidden text-xs bg-gray-55">
                  <button
                    onClick={() => setFontSize(Math.max(12, fontSize - 2))}
                    className="px-2 py-0.5 hover:bg-gray-200 active:scale-90 border-r border-gray-300 font-bold text-gray-800"
                    title={tLocal("fontSmaller")}
                  >
                    A-
                  </button>
                  <span className="px-2 font-semibold text-gray-800">{fontSize}px</span>
                  <button
                    onClick={() => setFontSize(Math.min(28, fontSize + 2))}
                    className="px-2 py-0.5 hover:bg-gray-200 active:scale-90 font-bold text-gray-800"
                    title={tLocal("fontLarger")}
                  >
                    A+
                  </button>
                </div>

                {/* TTS — Dengarkan Pasal */}
                <button
                  onClick={speakChapter}
                  disabled={!loadedChapter}
                  className={`text-xs font-bold flex items-center gap-1.5 px-3 py-1.5 rounded-xl border transition-all active:scale-95 disabled:opacity-40 shadow-sm ${
                    isSpeaking
                      ? "bg-red-50 text-red-500 border-red-300 animate-pulse"
                      : "bg-teal-50 text-teal-700 border-teal-300 hover:bg-teal-100"
                  }`}
                  title={isSpeaking ? tLocal("stop") : tLocal("listen")}
                >
                  <span>{isSpeaking ? "⏹" : "🔊"}</span>
                  <span>{isSpeaking ? tLocal("stop") : tLocal("listen")}</span>
                </button>

                <span className="text-[10px] text-gray-600 bg-gray-100 border border-gray-200 px-2 py-0.5 rounded font-bold uppercase">
                  {
                    language === "zh"
                      ? "CUV"
                      : language === "en"
                      ? (USE_WEB_BIBLE ? "WEB" : "BSB")
                      : (USE_WEB_BIBLE ? "WEB-AI" : "AYT")
                  }
                </span>
              </div>
            </div>

            {/* Chapter Text Scroll Container */}
            <div className="space-y-4 leading-relaxed text-gray-800" style={{ fontSize: `${fontSize}px` }}>
              {loadedChapter.chapter?.content?.map((item: any, idx: number) => {
                if (item.type === "heading") {
                  return (
                    <h3 key={idx} className="font-extrabold text-black pt-4 border-b border-gray-150 pb-1 mt-3 font-serif">
                      {item.content?.join(" ")}
                    </h3>
                  );
                }
                if (item.type === "verse") {
                  const isHighlighted = highlightedVerses.includes(Number(item.number));
                  const text = extractBibleText(item.content);
                  return (
                    <p
                      key={idx}
                      id={`v-${item.number}`}
                      className={`py-2 px-3 rounded transition-colors ${
                        isHighlighted
                          ? "bg-amber-100/70 border-l-3 border-amber-500 text-black font-semibold"
                          : "hover:bg-gray-50"
                      }`}
                    >
                      <sup className="text-xs font-bold text-teal-700 mr-2">{item.number}</sup>
                      {text}
                    </p>
                  );
                }
                return null;
              })}
            </div>
          </div>
        )}

        {/* Keyword Search List View */}
        {keywordResults.length > 0 && !loading && (
          <div className="space-y-4">
            <div className="border-b border-gray-200 pb-3">
              <h2 className="text-sm font-bold text-black uppercase tracking-wider">
                {tLocal("resultsTitle").replace("{count}", keywordResults.length.toString())}
              </h2>
            </div>
            <div className="divide-y divide-gray-100 max-h-[500px] overflow-y-auto pr-1">
              {keywordResults.map((verse) => (
                <div
                  key={verse.id}
                  onClick={() => {
                    // Navigate or load the full chapter
                    loadChapterData(verse.book, verse.chapter.toString(), verse.verse.toString());
                    setSearchQuery(`${getBookName(verse.book || "", language)} ${verse.chapter}:${verse.verse}`);
                  }}
                  className="py-3.5 hover:bg-gray-50 cursor-pointer transition-all px-2.5 rounded-lg text-left"
                >
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-xs font-extrabold text-teal-700 uppercase font-serif">
                      {getBookName(verse.book || "", language)} {verse.chapter}:{verse.verse}
                    </span>
                    <span className="text-[9px] text-gray-500 bg-gray-100 px-1.5 py-0.2 rounded font-bold">
                      {verse.translation}
                    </span>
                  </div>
                  <p className="text-sm text-gray-900 leading-relaxed italic">
                    &ldquo;{verse.text}&rdquo;
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function DedicatedBiblePage() {
  return (
    <div className="min-h-screen bg-white font-sans text-slate-900 overflow-y-auto">
      <Suspense fallback={
        <div className="min-h-screen flex flex-col items-center justify-center bg-white text-gray-600">
          <span className="w-8 h-8 border-4 border-teal-600 border-t-transparent rounded-full animate-spin mb-3"></span>
          <span>Inisialisasi Alkitab...</span>
        </div>
      }>
        <BibleContent />
      </Suspense>
    </div>
  );
}
