name = "grace-daily-ai"
main = "index.js"
compatibility_date = "2023-01-01"

[vars]
# API Providers Key
# Anda dapat memasukkan nilai langsung di sini atau menggunakan perintah 'wrangler secret put KEY' untuk keamanan maksimal.
GROQ_API_KEY = ""
GROQ_API_KEY_BACKUP = ""
OPENROUTER_API_KEY = ""
OPENROUTER_API_KEY_BACKUP = ""
OPENROUTER_API_KEY_SECOND_BACKUP = ""
MISTRAL_API_KEY = ""
NVIDIA_API_KEY = ""
NVIDIA_API_KEY_BACKUP = ""
GEMINI_API_KEY = ""
OPENAI_API_KEY = ""

# Model configurations
GROQ_MODEL = "llama-3.3-70b-versatile"
OPENROUTER_MODEL = "google/gemini-2.5-flash"
MISTRAL_MODEL = "mistral-small-latest"
NVIDIA_MODEL = "meta/llama-3.3-70b-instruct"
GEMINI_MODEL = "gemini-1.5-flash"
OPENAI_MODEL = "gpt-4o-mini"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "renungan-life"

[[d1_databases]]
binding = "DB"
database_name = "gracedaily-db"
database_id = "02913987-6b3d-45c9-890a-4f0a43f43b6a"
migrations_dir = "migrations"
